apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xfiles-app

resources:
  - xfiles-frontend-service.yaml
  - xfiles-frontend-ingress.yaml
  - xfiles-app-deployment.yaml
  - postgres-deployment.yaml
  - postgres-pvc.yaml
  - postgres-init-configmap.yaml
  - postgres-service.yaml  # ✅ Make sure this file exists

configMapGenerator:
  - name: postgres-init-script
    files:
      - postgres-init-configmap.yaml

commonLabels:
  app: xfiles
